title: Project

columns:
  main:
    width: 2/3
    sections:
      main:
        type: fields
        fields:
          gallery:
            label: Gallery
            type: files
            uploads: image
            required: true
            layout: cards
            image:
              ratio: 16/9
              cover: true
          description:
            type: textarea
            size: medium
            required: true
      details:
        type: fields
        fields:
          projectType:
            width: 1/2
            label: Project Type
            type: tags
            options: query
            query: page.siblings.pluck("projectType", ",", true)
            required: true
          scopes:
            width: 1/2
            label: Scopes
            type: tags
            options: query
            query: page.siblings.pluck("scopes", ",", true)
            required: true
          tools:
            width: 1/2
            label: Tools used
            type: tags
            options: query
            query: page.siblings.pluck("tools", ",", true)
          technologies:
            width: 1/2
            label: Technologies used
            type: tags
            options: query
            query: page.siblings.pluck("technologies", ",", true)
          startDate:
            width: 1/2
            label: Start Date
            type: date
            required: true
          endDate:
            width: 1/2
            label: End Date
            type: date
  meta:
    width: 1/3
    sections:
      files:
        type: files
      meta:
        type: fields
        fields:
          teamMembers:
            width: 1/2
            label: Team Members
            type: structure
            fields:
              name:
                label: Name
                type: text
                required: true
          links:
            width: 1/2
            label: Links
            type: structure
            fields:
              name:
                label: Name
                type: text
                required: true
              url:
                label: URL
                type: url
                required: true
