tabs:
  content:
    label: Content
    icon: text
    columns:
      main:
        width: 2/3
        sections:
          drafts:
            type: pages
            headline: Drafts
            status: draft
          unlisted:
            type: pages
            headline: Unlisted
            status: unlisted
          listed:
            type: pages
            headline: Listed
            status: listed
      about:
        width: 1/3
        sections:
          about:
            type: fields
            fields:
              footerMenu:
                type: pages
                label: Footer Menu Items
                translate: false
              copyright:
                type: text
                required: true
  seo: seo/site
