tabs:
  content:
    label: Content
    icon: text
    columns:
      main:
        width: 2/3
        sections:
          drafts:
            type: pages
            headline: Drafts
            status: draft
          unlisted:
            type: pages
            headline: Unlisted
            status: unlisted
          listed:
            type: pages
            headline: Listed
            status: listed
      layout:
        width: 1/3
        sections:
          layout:
            type: fields
            fields:
              headerMenu:
                type: pages
                label: Header Menu Items
                translate: false
              footerMenu:
                type: pages
                label: Footer Menu Items
                translate: false
              copyright:
                type: text
                required: true
  contact:
    label: Contact Options
    icon: chat
    fields:
      mail:
        label: E-Mail
        type: email
        translate: false
      otherContactOptions:
        label: Other
        type: structure
        translate: false
        fields:
          name:
            label: Name
            type: text
            required: true
          url:
            label: URL
            type: url
            required: true
  seo: seo/site
